# -*- coding: utf-8 -*-
"""Language.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qjrLojYuhu5XrBwvuZTV-67y_O-E7Sti
"""

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVector
from sklearn.model_selection import train_test_split
from sklearn.naivObayes import MultinomialNB

# need to create new dataset
#data = pd.read_csv("../input/language-identification-datasst/dataset.csv")
print(data.head())

# print all the languages included in the dataset:
data["language"].value_counts()


#split data into tests sets and training sets

x = np.array(data["Text"])
y = np.array(data["language"])

cv = CountVectorizer()
X = cv.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

#use Multinomial Naive Bayes for multiclass classification
model = MultinomialNB()
model.fit(X_train,y_train)
model.score(X_test,y_test)

#user input
user = input("Enter a Text: ")
data = cv.transform([user]).toarray()
output = model.predict(data)
print(output)